### ISSUE TITLE
Error get token facebook.

### ISSUE THREAD

**Issue by mdmunir** [yiisoft/yii2-authclient#142]
### What steps will reproduce the problem?
```php
$client = \Yii::$app->authClientCollection->clients['facebook'];
$token = $client->authenticateClient();
```
### What's expected?
Got `access_token`

### What do you get instead?
![screenshot from 2016-10-14 14 40 32](https://cloud.githubusercontent.com/assets/5828252/19379503/6f2dad1a-921c-11e6-9019-40a06bca025b.png)

### Additional info
```
exception 'yii\base\InvalidParamException' with message 'Unrecognized format ''' in /home/mdmunir/projects/php/psmx/yii2-piknikio/vendor/yiisoft/yii2-httpclient/Client.php:169 Stack trace: 
#0 /home/mdmunir/projects/php/psmx/yii2-piknikio/vendor/yiisoft/yii2-httpclient/Response.php(191): yii\httpclient\Client->getParser(NULL) 
#1 /home/mdmunir/projects/php/psmx/yii2-piknikio/vendor/yiisoft/yii2-httpclient/Response.php(33): yii\httpclient\Response->getParser() 
#2 /home/mdmunir/projects/php/psmx/yii2-piknikio/vendor/yiisoft/yii2-authclient/BaseOAuth.php(224): yii\httpclient\Response->getData() 
#3 /home/mdmunir/projects/php/psmx/yii2-piknikio/vendor/yiisoft/yii2-authclient/OAuth2.php(230): yii\authclient\BaseOAuth->sendRequest(Object(yii\httpclient\Request)) 
#4 /home/mdmunir/projects/php/psmx/yii2-piknikio/app/controllers/api/v1/UserController.php(43): yii\authclient\OAuth2->authenticateClient() 
#5 [internal function]: app\controllers\api\v1\UserController->actionInfoToken('abcde') 
#6 /home/mdmunir/projects/php/psmx/yii2-piknikio/vendor/yiisoft/yii2/base/InlineAction.php(55): call_user_func_array(Array, Array) 
#7 /home/mdmunir/projects/php/psmx/yii2-piknikio/vendor/yiisoft/yii2/base/Controller.php(154): yii\base\InlineAction->runWithParams(Array) 
#8 /home/mdmunir/projects/php/psmx/yii2-piknikio/vendor/yiisoft/yii2/base/Module.php(454): yii\base\Controller->runAction('info-token', Array) 
#9 /home/mdmunir/projects/php/psmx/yii2-piknikio/vendor/yiisoft/yii2/web/Application.php(100): yii\base\Module->runAction('api/v1/user/inf...', Array) 
#10 /home/mdmunir/projects/php/psmx/yii2-piknikio/vendor/yiisoft/yii2/base/Application.php(375): yii\web\Application->handleRequest(Object(yii\web\Request)) 
#11 /home/mdmunir/projects/php/psmx/yii2-piknikio/app/web/index.php(18): yii\base\Application->run() 
#12 {main}
```

| Q                | A
| ---------------- | ---
| Yii vesion       | dev-master
| Yii Authclient version | dev-master
| PHP version      | 5.6
| Operating system | debian 7

**Comment by klimov-paul** [comment]
Migrated to https://github.com/yiisoft/yii2-httpclient/issues/73
