### ISSUE TITLE
Auth error: undefined

### ISSUE THREAD

**Issue by indicalabs** [yiisoft/yii2-authclient#167]
### What steps will reproduce the problem?
Followed http://www.yiiframework.com/doc-2.0/yii-authclient-clients-googlehybrid.html
The Google client was working fine , but there is an error when I changed the `'class' to 'yii\authclient\clients\GoogleHybrid',`
### What's expected?
Display of Sign in with Google button
### What do you get instead?

```
[error][yii\base\Exception] yii\base\Exception: Auth error: undefined in /var/www/html/mysite/vendor/yiisoft/yii2-authclient/AuthAction.php:349
Stack trace:
#0 /var/www/html/mysite/vendor/yiisoft/yii2-authclient/AuthAction.php(192): yii\authclient\AuthAction->authOAuth2(Object(yii\authclient\clients\GoogleHybrid))
#1 /var/www/html/mysite/vendor/yiisoft/yii2-authclient/AuthAction.php(177): yii\authclient\AuthAction->auth(Object(yii\authclient\clients\GoogleHybrid))
#2 [internal function]: yii\authclient\AuthAction->run()
#3 /var/www/html/mysite/vendor/yiisoft/yii2/base/Action.php(94): call_user_func_array(Array, Array)
#4 /var/www/html/mysite/vendor/yiisoft/yii2/base/Controller.php(156): yii\base\Action->runWithParams(Array)
#5 /var/www/html/mysite/vendor/yiisoft/yii2/base/Module.php(523): yii\base\Controller->runAction('auth', Array)
#6 /var/www/html/mysite/vendor/yiisoft/yii2/web/Application.php(102): yii\base\Module->runAction('site/auth', Array)
#7 /var/www/html/mysite/vendor/yiisoft/yii2/base/Application.php(379): yii\web\Application->handleRequest(Object(yii\web\Request))
#8 /var/www/html/mysite/frontend/web/index.php(17): yii\base\Application->run()
#9 {main}
2017-07-05 09:07:48 [10.255.0.2][-][k5ocmd2b3ae6ncsjips2s3et09][info][application] $_GET = [
    'authclient' => 'google'
    'error' => 'immediate_failed'
    'error_description' => 'undefined'
]
```

### Additional info

| Q                | A
| ---------------- | ---
| Yii vesion       | ~2.0.12
| PHP version      |  	7.1.6-r0 
| Operating system | Alpine with Docker - but accessing on mac with firefox

**Comment by klimov-paul** [comment]
Resolved by commit 595c2933b46e0f72143702214dc9777f8abb4ad8
