### ISSUE TITLE
OpenID Connect Error: Token not provided

### ISSUE THREAD

**Issue by gallexme** [yiisoft/yii2-authclient#224]
### What steps will reproduce the problem?
1. keycloak as open id connect provider
2.  
```'authClientCollection' => [
            'class' => 'yii\authclient\Collection',
            'clients' => [
              'scaleit' => [
                'class' => 'app\components\OndicsOpenIdConnect',
                'issuerUrl' => 'https://smth/auth/realms/master',
                'clientId' => 'de-smth-sso',
                'clientSecret' => 'b8cssssssssss439-9ffe-b466ed0888fa',
                'name' => 'sso',
                'title' => 'SSO',
              ],
            ],
          ],
```
### What's expected?
Keycloak Login Mask then loginned

### What do you get instead?
Keycloak Login mask then Error from Keycloak:

Request failed with code: 400, message: {"error":"invalid_request","error_description":"Token not provided"}

### Additional info
works with other openid clients like resty-openidc

| Q                       | A
| ----------------------- | ---
| Yii version             |
| Yii Auth Client version | 2.1.5
| Yii HTTP Client version |
| PHP version             | 7.2
| Operating system        | linux

```
2018-05-30 14:20:02 [172.19.0.1][-][c29383f50716c02d742809f85401bb13][error][yii\authclient\InvalidResponseException] yii\authclient\InvalidResponseException: Request failed with code: 400, message: {"error":"invalid_request","error_description":"Token not provided"} in /var/www/vendor/yiisoft/yii2-authclient/src/BaseOAuth.php:221
web_1                 | Stack trace:
web_1                 | #0 /var/www/vendor/yiisoft/yii2-authclient/src/BaseOAuth.php(329): yii\authclient\BaseOAuth->sendRequest(Object(yii\httpclient\Request))
web_1                 | #1 /var/www/vendor/yiisoft/yii2-authclient/src/OpenIdConnect.php(261): yii\authclient\BaseOAuth->api('https://sso.ran...', 'GET')
web_1                 | #2 /var/www/vendor/yiisoft/yii2-authclient/src/BaseClient.php(174): yii\authclient\OpenIdConnect->initUserAttributes()
web_1                 | #3 /var/www/html/components/AuthHandler.php(27): yii\authclient\BaseClient->getUserAttributes()
web_1                 | #4 /var/www/html/controllers/SiteController.php(57): app\components\AuthHandler->handle()
web_1                 | #5 [internal function]: app\controllers\SiteController->onAuthSuccess(Object(app\components\OndicsOpenIdConnect))
web_1                 | #6 /var/www/vendor/yiisoft/yii2-authclient/src/AuthAction.php(231): call_user_func(Array, Object(app\components\OndicsOpenIdConnect))
web_1                 | #7 /var/www/vendor/yiisoft/yii2-authclient/src/AuthAction.php(394): yii\authclient\AuthAction->authSuccess(Object(app\components\OndicsOpenIdConnect))
web_1                 | #8 /var/www/vendor/yiisoft/yii2-authclient/src/AuthAction.php(209): yii\authclient\AuthAction->authOAuth2(Object(app\components\OndicsOpenIdConnect))
web_1                 | #9 /var/www/vendor/yiisoft/yii2-authclient/src/AuthAction.php(194): yii\authclient\AuthAction->auth(Object(app\components\OndicsOpenIdConnect))
web_1                 | #10 [internal function]: yii\authclient\AuthAction->run()
web_1                 | #11 /var/www/vendor/yiisoft/yii2/base/Action.php(94): call_user_func_array(Array, Array)
web_1                 | #12 /var/www/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\Action->runWithParams(Array)
web_1                 | #13 /var/www/vendor/yiisoft/yii2/base/Module.php(528): yii\base\Controller->runAction('auth', Array)
web_1                 | #14 /var/www/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('site/auth', Array)
web_1                 | #15 /var/www/vendor/yiisoft/yii2/base/Application.php(386): yii\web\Application->handleRequest(Object(yii\web\Request))
web_1                 | #16 /var/www/html/web/index.php(32): yii\base\Application->run()
web_1                 | #17 {main}
web_1                 | 2018-05-30 14:20:02 [172.19.0.1][-][c29383f50716c02d742809f85401bb13][info][yii\web\Session::open] Session started
web_1                 | 2018-05-30 14:20:02 [172.19.0.1][-][c29383f50716c02d742809f85401bb13][info][yii\httpclient\StreamTransport::send] POST https://smth/auth/realms/master/protocol/openid-connect/token
web_1                 | Authorization: Basic ZGUtb25kaWNzLXNzbzpiOGMyYTdlYy05NDhhLTQ0MzktOWZmZS1iNDY2ZWQwODg4ZmE=
web_1                 | Content-Type: application/x-www-form-urlencoded; charset=UTF-8
```

**Comment by samdark** [comment]
Try with master branch. If it doesn't work, the only way to fix it is to debug it yourself.

**Comment by gallexme** [comment]
works with master @samdark  :+1:
